name: Publish Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup publish to npmjs.org
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Typecheck
        run: yarn tsc --noEmit
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Set Version ${{ github.event.release.tag_name }}
        run: yarn version ${{ github.event.release.tag_name }}
      - name: Build Package
        run: yarn build
      - name: Publish Package to npmjs.org
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup publish to Github Packages
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish Package to Github Packages
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
