name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Setup Git
        run: git config --global user.name "GitHub CI bot" && git config --global user.email "github-ci-bot@example.com"
      - name: Set Version ${{ github.event.release.tag_name }}
        run: yarn version ${{ github.event.release.tag_name }}
      - name: Build Package
        run: yarn build
      - name: Publish Package
        run: yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name:
        run: git push
        env:
          github-token: ${{ secrets.GITHUB_TOKEN }}
