name: Publish Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install pnpm
        uses: pnpm/action-setup@v5
      - name: Setup publish to npmjs.org
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile
      - name: Format Check
        run: pnpm format:check
      - name: Type Check
        run: pnpm types:check
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build Package
        run: pnpm build
      - name: Publish Package to npmjs.org
        run: pnpm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup publish to Github Packages
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ldrick'
      - name: Publish Package to Github Packages
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
