name: Publish Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup publish to npmjs.org
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: Format Check
        run: npm run check:format
      - name: Type Check
        run: npm run check:types
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build Package
        run: npm run build
      - name: Publish Package to npmjs.org
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup publish to Github Packages
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ldrick'
      - name: Publish Package to Github Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
